const BucketListActions = {
    FETCH_BUCKET_LIST: 'FETCH_BUCKET_LIST',
    FETCH_BUCKET_LIST_SUCCESS: 'FETCH_BUCKET_LIST_SUCCESS',
    FETCH_BUCKET_LIST_FAILURE: 'FETCH_BUCKET_LIST_FAILURE',
    ADD_LIST_ITEM: 'ADD_LIST_ITEM',
    REMOVE_LIST_ITEM: 'REMOVE_LIST_ITEM',
    UPDATE_LIST_ITEMS_SUCCESS: 'UPDATE_LIST_ITEMS_SUCCESS',
    BUCKET_LIST_OPERATION_ERROR: 'BUCKET_LIST_OPERATION_ERROR'
};

export default BucketListActions;